id: P009272
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20841
  title: ངམ་རིང་ཆོས་སྡེའི་ལོ་རྒྱུས
  author: ''
  volumes:
    d30d30ff74f24ca299be17b89c3de9df:
      image_group_id: I5675
      title: ''
      volume_number: 1
      total_pages: 127
      base_file: v001.txt
