id: I069FD89A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:06:18+00:00'
last_modified: '2022-06-08T09:50:28.310640+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20841
  title: ངམ་རིང་ཆོས་སྡེའི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B883:
      image_group_id: I5675
      title: ''
      total_pages: 127
      order: 1
      base_file: B883.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
